spring.application.name=finance-buddy-06-2026

spring.datasource.url=jdbc:mysql://localhost:3306/finance_buddy
spring.datasource.username=root
spring.datasource.password=yearup

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true